/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
/**
 *
 * @author Admin
 */
public class frm_QuanLyChung extends javax.swing.JFrame {
    /**
     * Creates new form frm_QuanLyChung
     */  
    public String layQuyen;
    public frm_QuanLyChung(String layQuyen) {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("General Management");  
        this.layQuyen=layQuyen;
        this.txt_quyen.setText(layQuyen);  
    }

    private frm_QuanLyChung() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_hoaDon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_NhanVien = new javax.swing.JButton();
        btn_Order = new javax.swing.JButton();
        btn_ban = new javax.swing.JButton();
        btn_MonAn = new javax.swing.JButton();
        btn_KhachHang = new javax.swing.JButton();
        btn_dangXuat = new javax.swing.JButton();
        txt_quyen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_hoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_hoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print.png"))); // NOI18N
        btn_hoaDon.setText("Hóa đơn");
        btn_hoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoaDonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Chung");

        btn_NhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Account_50px.png"))); // NOI18N
        btn_NhanVien.setText("Nhân viên");
        btn_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhanVienActionPerformed(evt);
            }
        });

        btn_Order.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-money-bag-50.png"))); // NOI18N
        btn_Order.setText("Order");
        btn_Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OrderActionPerformed(evt);
            }
        });

        btn_ban.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ban.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ban(1).png"))); // NOI18N
        btn_ban.setText("Bàn");
        btn_ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_banActionPerformed(evt);
            }
        });

        btn_MonAn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_MonAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-restaurant-menu-50.png"))); // NOI18N
        btn_MonAn.setText("Món ăn");
        btn_MonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MonAnActionPerformed(evt);
            }
        });

        btn_KhachHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cafe.png"))); // NOI18N
        btn_KhachHang.setText("Khách hàng");
        btn_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhachHangActionPerformed(evt);
            }
        });

        btn_dangXuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_dangXuat.setText("Đăng xuất");
        btn_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangXuatActionPerformed(evt);
            }
        });

        txt_quyen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_quyen.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_dangXuat)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_MonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_hoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ban, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txt_quyen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_dangXuat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_quyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ban, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhanVienActionPerformed
        // TODO add your handling code here:        
        frm_QLNhanVien qlnv = new frm_QLNhanVien(txt_quyen.getText());
        qlnv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_NhanVienActionPerformed

    private void btn_OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrderActionPerformed
        frm_QLOrder qlod = new frm_QLOrder(txt_quyen.getText());
        qlod.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_OrderActionPerformed

    private void btn_banActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_banActionPerformed
        frm_QLBanAn qlba = new frm_QLBanAn(txt_quyen.getText());
        qlba.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_banActionPerformed

    private void btn_MonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MonAnActionPerformed
        frm_QLMonAn qlma = new frm_QLMonAn(txt_quyen.getText());
        qlma.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_MonAnActionPerformed

    private void btn_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangXuatActionPerformed
        // TODO add your handling code here:
        frm_QuanLyDangNhap qldn = new frm_QuanLyDangNhap();
        qldn.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_dangXuatActionPerformed

    private void btn_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhachHangActionPerformed
        frm_QLKhachHang qlkh = new frm_QLKhachHang(txt_quyen.getText());
        qlkh.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_KhachHangActionPerformed

    private void btn_hoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoaDonActionPerformed
        // TODO add your handling code here:
        frm_QLHoaDon qlhd = new frm_QLHoaDon(txt_quyen.getText());
        qlhd.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_hoaDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_QuanLyChung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_KhachHang;
    private javax.swing.JButton btn_MonAn;
    private javax.swing.JButton btn_NhanVien;
    private javax.swing.JButton btn_Order;
    private javax.swing.JButton btn_ban;
    private javax.swing.JButton btn_dangXuat;
    private javax.swing.JButton btn_hoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_quyen;
    // End of variables declaration//GEN-END:variables
}
