/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import DAO.GiamSatUser_DAO;
import POJO.GiamSatUserTheoLogin;
import POJO.GiamSatUserTheoLogout;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class frm_GiamSatTriggerTungPhan extends javax.swing.JFrame {
    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    DefaultTableModel tblModel;
    
    Vector tblData2 = new Vector();
    Vector tblTitle2 = new Vector();
    DefaultTableModel tblModel2;
    
    static ArrayList<GiamSatUserTheoLogin> dsgs2 = GiamSatUser_DAO.getDSGiamSatTheoLogin();
    static ArrayList<GiamSatUserTheoLogout> dsgs3 = GiamSatUser_DAO.getDSGiamSatTheoLogout();
    private String layQuyenNV;
    /**
     * Creates new form frm_GiamSatTriggerTungPhan
     */
    public frm_GiamSatTriggerTungPhan(String layQuyenNV) {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("User monitoring");
        
        bangGiamSat();
        laydulieuGSTheoLogin(dsgs2);
        
        bangGiamSat2();
        laydulieuGSTheoLogout(dsgs3);
        
        this.layQuyenNV=layQuyenNV;
        this.txt_quyen1.setText(layQuyenNV); 
    }

    private frm_GiamSatTriggerTungPhan() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    public void bangGiamSat() {
        tblTitle.add("Key ID");
        tblTitle.add("Username");
        tblTitle.add("Login time");
        tblTitle.add("Hoạt động");
    }
    public void laydulieuGSTheoLogin(ArrayList<GiamSatUserTheoLogin> dsgs2) {
        tblData.removeAllElements();
        for (GiamSatUserTheoLogin b : dsgs2) {
            Vector v = new Vector();
            v.add(b.getKey_id());
            v.add(b.getUsername());
            v.add(b.getLogin_time());
            v.add(b.getHoat_dong());
            tblData.add(v);
        }
        tb_giamSatTheoLogin.setModel(new DefaultTableModel(tblData, tblTitle));
    }
    
    public void bangGiamSat2() {
        tblTitle2.add("Key ID");
        tblTitle2.add("Username");
        tblTitle2.add("Logout time");
        tblTitle2.add("Hoạt động");
    }
    public void laydulieuGSTheoLogout(ArrayList<GiamSatUserTheoLogout> dsgs3) {
        tblData2.removeAllElements();
        for (GiamSatUserTheoLogout b : dsgs3) {
            Vector v = new Vector();
            v.add(b.getKey_id());
            v.add(b.getUsername());
            v.add(b.getLogout_time());
            v.add(b.getHoat_dong());
            tblData2.add(v);
        }
        tb_giamSatTheoLogout.setModel(new DefaultTableModel(tblData2, tblTitle2));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_giamSatTheoLogin = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_quyen1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_giamSatTheoLogout = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_giamSatTheoLogin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_giamSatTheoLogin);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Trở về");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Tải lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txt_quyen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_quyen1.setEnabled(false);

        tb_giamSatTheoLogout.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_giamSatTheoLogout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_quyen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_quyen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frm_QLNhanVien qlnv = new frm_QLNhanVien(layQuyenNV);
        qlnv.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        GiamSatUser_DAO.getDSGiamSatTheoLogin();
        dsgs2 = GiamSatUser_DAO.getDSGiamSatTheoLogin(); // Cập nhật danh sách dsnv
        laydulieuGSTheoLogin(dsgs2);
        GiamSatUser_DAO.getDSGiamSatTheoLogout();
        dsgs3 = GiamSatUser_DAO.getDSGiamSatTheoLogout(); // Cập nhật danh sách dsnv
        laydulieuGSTheoLogout(dsgs3);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_GiamSatTriggerTungPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_GiamSatTriggerTungPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_GiamSatTriggerTungPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_GiamSatTriggerTungPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_GiamSatTriggerTungPhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_giamSatTheoLogin;
    private javax.swing.JTable tb_giamSatTheoLogout;
    private javax.swing.JTextField txt_quyen1;
    // End of variables declaration//GEN-END:variables
}
