/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import POJO.DBA_AUDIT_POLICIES;
import DAO.FGAAuditTrail_DAO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class frm_FGANhanVien extends javax.swing.JFrame {
    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    DefaultTableModel tblModel;         
   
    String s1[] = {"NHANVIEN", "KHACHHANG", "MONAN", "BANAN", "HOADON", "CHITIETHOADON"};
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(s1);
    
    static ArrayList<DBA_AUDIT_POLICIES> dap = FGAAuditTrail_DAO.LayThongTinChinhSachFGA();

    private String layQuyenNV;
    /**
     * Creates new form frm_FGANhanVien
     */
    public frm_FGANhanVien(String layQuyenNV) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        cbm_objName.setModel(model);
        
        bangGiamSat();
        laydulieuFGA(dap);
        
        this.layQuyenNV=layQuyenNV;
        this.txt_quyen1.setText(layQuyenNV); 
    }

    private frm_FGANhanVien() {
    }
    public void bangGiamSat() {
        tblTitle.add("Object_schema");
        tblTitle.add("Object_name");
        tblTitle.add("Policy_owner");
        tblTitle.add("Policy_name");
        tblTitle.add("Policy_column");      
    }
    public void laydulieuFGA(ArrayList<DBA_AUDIT_POLICIES> dap) {
        tblData.removeAllElements();
        for (DBA_AUDIT_POLICIES b : dap) {
            Vector v = new Vector();
            v.add(b.getObject_schema());
            v.add(b.getObject_name());
            v.add(b.getPolicy_owner());
            v.add(b.getPolicy_name());
            v.add(b.getPolicy_column());
            tblData.add(v);
        }
        tb_FGANhanVien.setModel(new DefaultTableModel(tblData, tblTitle));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_policyName = new javax.swing.JTextField();
        cbm_objName = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_xayDungChinhSach = new javax.swing.JButton();
        btn_xoaChinhSach = new javax.swing.JButton();
        btn_troVe = new javax.swing.JButton();
        btn_taiLai = new javax.swing.JButton();
        rdb_select = new javax.swing.JRadioButton();
        rdb_update = new javax.swing.JRadioButton();
        rdb_delete = new javax.swing.JRadioButton();
        rdb_insert = new javax.swing.JRadioButton();
        txt_quyen1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_auditColumn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_FGANhanVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("object name:");

        cbm_objName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("policy name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("audit column:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("statement types:");

        btn_xayDungChinhSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_xayDungChinhSach.setText("Xây dựng chính sách");
        btn_xayDungChinhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xayDungChinhSachActionPerformed(evt);
            }
        });

        btn_xoaChinhSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_xoaChinhSach.setText("Xóa chính sách");
        btn_xoaChinhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaChinhSachActionPerformed(evt);
            }
        });

        btn_troVe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_troVe.setText("Trở về");
        btn_troVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_troVeActionPerformed(evt);
            }
        });

        btn_taiLai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_taiLai.setText("Tải lại");
        btn_taiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taiLaiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdb_select);
        rdb_select.setText("Select");

        buttonGroup1.add(rdb_update);
        rdb_update.setText("Update");

        buttonGroup1.add(rdb_delete);
        rdb_delete.setText("Delete");

        buttonGroup1.add(rdb_insert);
        rdb_insert.setText("Insert");

        txt_quyen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_quyen1.setEnabled(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Bảng ghi chi tiết");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbm_objName, 0, 180, Short.MAX_VALUE)
                            .addComponent(txt_policyName)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(rdb_update, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdb_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rdb_select, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdb_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_auditColumn))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_xayDungChinhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_xoaChinhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txt_quyen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_taiLai)
                        .addGap(18, 18, 18)
                        .addComponent(btn_troVe)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbm_objName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_policyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_auditColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rdb_select)
                            .addComponent(rdb_insert))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdb_update)
                            .addComponent(rdb_delete)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_quyen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_xayDungChinhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_xoaChinhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_troVe)
                    .addComponent(btn_taiLai))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tb_FGANhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_FGANhanVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_troVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_troVeActionPerformed
        // TODO add your handling code here:
        frm_QLNhanVien qlnv = new frm_QLNhanVien(layQuyenNV);
        qlnv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_troVeActionPerformed

    private void btn_taiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taiLaiActionPerformed
        // TODO add your handling code here:
        FGAAuditTrail_DAO.LayThongTinChinhSachFGA();
        dap = FGAAuditTrail_DAO.LayThongTinChinhSachFGA(); // Cập nhật danh sách dsnv
        laydulieuFGA(dap);
    }//GEN-LAST:event_btn_taiLaiActionPerformed

    private void btn_xayDungChinhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xayDungChinhSachActionPerformed
        // TODO add your handling code here:
        String object_name = cbm_objName.getSelectedItem().toString();
        String policy_name = txt_policyName.getText().trim();
        String audit_column = txt_auditColumn.getText().trim();
        
        if(rdb_select.isSelected()==true){
            String sql = "{CALL DBMS_FGA.ADD_POLICY("
                    + "object_schema => 'NV001',"
                    + "object_name => '"+object_name+"',"
                    + "policy_name => '"+policy_name+"',"
                    + "audit_column => '"+audit_column+"',"
                    + "statement_types => 'SELECT',"
                    + "audit_trail => DBMS_FGA.DB+DBMS_FGA.EXTENDED)}";         
            if(FGAAuditTrail_DAO.ThucHienChucNang(sql) > 0 ){            
                JOptionPane.showMessageDialog(rootPane, "Thành công");
            }
        }
        if(rdb_insert.isSelected()==true){
            String sql = "{CALL DBMS_FGA.ADD_POLICY("
                    + "object_schema => 'NV001',"
                    + "object_name => '"+object_name+"',"
                    + "policy_name => '"+policy_name+"',"
                    + "audit_column => '"+audit_column+"',"
                    + "statement_types => 'INSERT',"
                    + "audit_trail => DBMS_FGA.DB+DBMS_FGA.EXTENDED)}";         
            if(FGAAuditTrail_DAO.ThucHienChucNang(sql) > 0 ){            
                JOptionPane.showMessageDialog(rootPane, "Thành công");
            }
        }
        if(rdb_update.isSelected()==true){
            String sql = "{CALL DBMS_FGA.ADD_POLICY("
                    + "object_schema => 'NV001',"
                    + "object_name => '"+object_name+"',"
                    + "policy_name => '"+policy_name+"',"
                    + "audit_column => '"+audit_column+"',"
                    + "statement_types => 'UPDATE',"
                    + "audit_trail => DBMS_FGA.DB+DBMS_FGA.EXTENDED)}";         
            if(FGAAuditTrail_DAO.ThucHienChucNang(sql) > 0 ){            
                JOptionPane.showMessageDialog(rootPane, "Thành công");
            }
        }
        if(rdb_delete.isSelected()==true){
            String sql = "{CALL DBMS_FGA.ADD_POLICY("
                    + "object_schema => 'NV001',"
                    + "object_name => '"+object_name+"',"
                    + "policy_name => '"+policy_name+"',"
                    + "audit_column => '"+audit_column+"',"
                    + "statement_types => 'DELETE',"
                    + "audit_trail => DBMS_FGA.DB+DBMS_FGA.EXTENDED)}";         
            if(FGAAuditTrail_DAO.ThucHienChucNang(sql) > 0 ){            
                JOptionPane.showMessageDialog(rootPane, "Thành công");
            }
        }
    }//GEN-LAST:event_btn_xayDungChinhSachActionPerformed

    private void btn_xoaChinhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaChinhSachActionPerformed
        // TODO add your handling code here:
        String object_name = cbm_objName.getSelectedItem().toString();
        String policy_name = txt_policyName.getText().trim();
        
        if(rdb_select.isSelected()==true){
            String sql = "{CALL DBMS_FGA.DROP_POLICY("
                    + "object_schema => 'NV001',"
                    + "object_name => '"+object_name+"',"
                    + "policy_name => '"+policy_name+"')}";         
            if(FGAAuditTrail_DAO.ThucHienChucNang(sql) > 0 ){    
                JOptionPane.showMessageDialog(rootPane, "Thành công");
            }
        }
        if(rdb_insert.isSelected()==true){
            String sql = "{CALL DBMS_FGA.DROP_POLICY("
                    + "object_schema => 'NV001',"
                    + "object_name => '"+object_name+"',"
                    + "policy_name => '"+policy_name+"')}";         
            if(FGAAuditTrail_DAO.ThucHienChucNang(sql) > 0 ){    
                JOptionPane.showMessageDialog(rootPane, "Thành công");
            }
        }
        if(rdb_update.isSelected()==true){
            String sql = "{CALL DBMS_FGA.DROP_POLICY("
                    + "object_schema => 'NV001',"
                    + "object_name => '"+object_name+"',"
                    + "policy_name => '"+policy_name+"')}";         
            if(FGAAuditTrail_DAO.ThucHienChucNang(sql) > 0 ){    
                JOptionPane.showMessageDialog(rootPane, "Thành công");
            }
        }
        if(rdb_delete.isSelected()==true){
            String sql = "{CALL DBMS_FGA.DROP_POLICY("
                    + "object_schema => 'NV001',"
                    + "object_name => '"+object_name+"',"
                    + "policy_name => '"+policy_name+"')}";         
            if(FGAAuditTrail_DAO.ThucHienChucNang(sql) > 0 ){    
                JOptionPane.showMessageDialog(rootPane, "Thành công");
            }
        }
    }//GEN-LAST:event_btn_xoaChinhSachActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frm_BangGhiNhanVienFGA bgNV = new frm_BangGhiNhanVienFGA(layQuyenNV);
        bgNV.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_FGANhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_FGANhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_FGANhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_FGANhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_FGANhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_taiLai;
    private javax.swing.JButton btn_troVe;
    private javax.swing.JButton btn_xayDungChinhSach;
    private javax.swing.JButton btn_xoaChinhSach;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbm_objName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdb_delete;
    private javax.swing.JRadioButton rdb_insert;
    private javax.swing.JRadioButton rdb_select;
    private javax.swing.JRadioButton rdb_update;
    private javax.swing.JTable tb_FGANhanVien;
    private javax.swing.JTextField txt_auditColumn;
    private javax.swing.JTextField txt_policyName;
    private javax.swing.JTextField txt_quyen1;
    // End of variables declaration//GEN-END:variables
}
