/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.NhanVien_DAO;
import POJO.NhanVien;
import java.security.InvalidKeyException;
import java.security.KeyFactory;
import java.security.NoSuchAlgorithmException;
import java.security.PublicKey;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.X509EncodedKeySpec;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public final class frm_QLNhanVien extends javax.swing.JFrame {
    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    DefaultTableModel tblModel;
    
    private frm_QuanLyChung qlc;
    static ArrayList<NhanVien> dsnv = NhanVien_DAO.LayThongTinNhanVien();
    /**
     * Creates new form frm_QLNhanVien
     */
    public String layQuyenNV;
    public frm_QLNhanVien(String layQuyenNV) {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Employee Manager");
        bangNhanVien();
            
        this.layQuyenNV=layQuyenNV;
        this.txt_quyen1.setText(layQuyenNV); 
        
        String quyenNV = txt_quyen1.getText();
        if("Admin".equals(quyenNV)){
            laydulieuNV(dsnv);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Bạn không đủ quyền hạn để coi thông tin này");
        }
        
    }  

    private frm_QLNhanVien() {
    }

    public void bangNhanVien() {
        tblTitle.add("MANV");
        tblTitle.add("TENNV");
        tblTitle.add("GIOITINH");
        tblTitle.add("NGAYSINH");
        tblTitle.add("DIACHI");
        tblTitle.add("SODT");
        tblTitle.add("EMAIL");
        tblTitle.add("PASSWORD");
        tblTitle.add("QUYEN");
    }
    public void laydulieuNV(ArrayList<NhanVien> dsnv) {
        tblData.removeAllElements();
        for (NhanVien b : dsnv) {
            Vector v = new Vector();
            v.add(b.getMANV());
            v.add(b.getTENNV());
            v.add(b.getGIOITINH());
            v.add(b.getNGAYSINH());
            v.add(b.getDIACHI());
            v.add(b.getSODT());
            v.add(b.getEMAIL());
            v.add(b.getPASS());
            v.add(b.getQUYEN());
            tblData.add(v);
        }
        tb_danhSachNhanVien.setModel(new DefaultTableModel(tblData, tblTitle));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        txt_timKiemTheoTen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_danhSachNhanVien = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnTroLai = new javax.swing.JButton();
        txt_quyen1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_maNV = new javax.swing.JTextField();
        txt_tenNV = new javax.swing.JTextField();
        txt_gioiTinh = new javax.swing.JTextField();
        btn_xoaNV = new javax.swing.JButton();
        btn_suaNV = new javax.swing.JButton();
        btn_themNV = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_ngaySinh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_soDT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_diaChi = new javax.swing.JTextField();
        txt_quyen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        btn_taiLai = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mn_giamSatTrigger = new javax.swing.JMenuItem();
        mn_giamSatSA = new javax.swing.JMenuItem();
        mn_standardAudit = new javax.swing.JMenuItem();
        mn_giamSatThietBi = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mn_giamSatTriggerTungPhan = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mn_giamSatAudit = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_danhSachNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_danhSachNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_danhSachNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_danhSachNhanVien);

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quản Lý Nhân Viên");

        btnTroLai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTroLai.setText("Trở lại");
        btnTroLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroLaiActionPerformed(evt);
            }
        });

        txt_quyen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_quyen1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnTroLai, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_quyen1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnTroLai, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_quyen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mã nhân viên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tên nhân viên:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Giới Tính:");

        btn_xoaNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_xoaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btn_xoaNV.setText("Xóa");
        btn_xoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaNVActionPerformed(evt);
            }
        });

        btn_suaNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_suaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view edit delete product.png"))); // NOI18N
        btn_suaNV.setText("Sửa");
        btn_suaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaNVActionPerformed(evt);
            }
        });

        btn_themNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_themNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new product.png"))); // NOI18N
        btn_themNV.setText("Thêm");
        btn_themNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themNVActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Password:");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Ngày sinh:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Số điện thoại:");
        jLabel9.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Địa chỉ:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Quyền:");
        jLabel11.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(74, 74, 74)
                        .addComponent(txt_quyen))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_themNV)
                                .addGap(3, 3, 3)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ngaySinh)
                            .addComponent(txt_maNV)
                            .addComponent(txt_tenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txt_gioiTinh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btn_xoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_suaNV))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_diaChi)
                            .addComponent(txt_soDT)
                            .addComponent(txt_email)
                            .addComponent(txt_pass))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_soDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_quyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_themNV, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_suaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        btn_taiLai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_taiLai.setText("Tải lại");
        btn_taiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taiLaiActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Đổi mật khẩu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Phân quyền");

        jMenuItem5.setText("Phân quyền riêng lẻ");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem1.setText("Phân nhóm quyền");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Giám sát (Huy)");

        mn_giamSatTrigger.setText("Giám sát User bằng Trigger");
        mn_giamSatTrigger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_giamSatTriggerActionPerformed(evt);
            }
        });
        jMenu2.add(mn_giamSatTrigger);

        mn_giamSatSA.setText("Hiển thị dữ liệu giám sát");
        mn_giamSatSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_giamSatSAActionPerformed(evt);
            }
        });
        jMenu2.add(mn_giamSatSA);

        mn_standardAudit.setText("Standard Audit");
        mn_standardAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_standardAuditActionPerformed(evt);
            }
        });
        jMenu2.add(mn_standardAudit);

        mn_giamSatThietBi.setText("Theo dõi thiết bị truy cập");
        mn_giamSatThietBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_giamSatThietBiActionPerformed(evt);
            }
        });
        jMenu2.add(mn_giamSatThietBi);

        jMenuItem8.setText("Tạo chính sách FGA");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Giám sát (An)");

        mn_giamSatTriggerTungPhan.setText("Giám sát User bằng Trigger từng phần");
        mn_giamSatTriggerTungPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_giamSatTriggerTungPhanActionPerformed(evt);
            }
        });
        jMenu5.add(mn_giamSatTriggerTungPhan);

        jMenuItem2.setText("Tạo chính sách FGA cho khách hàng");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        mn_giamSatAudit.setText("GIám sát User sử dụng Audting");
        mn_giamSatAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_giamSatAuditActionPerformed(evt);
            }
        });
        jMenu5.add(mn_giamSatAudit);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt_timKiemTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnTimKiem)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(btn_taiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTimKiem)
                            .addComponent(txt_timKiemTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_taiLai)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_danhSachNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_danhSachNhanVienMouseClicked
        int i = tb_danhSachNhanVien.getSelectedRow();
        String manv = tb_danhSachNhanVien.getValueAt(i, 0).toString().trim();
        String tennv = tb_danhSachNhanVien.getValueAt(i, 1).toString().trim();
        String gioitinh = tb_danhSachNhanVien.getValueAt(i, 2).toString().trim();
        String ngaysinh = tb_danhSachNhanVien.getValueAt(i, 3).toString().trim();
        String diachi = tb_danhSachNhanVien.getValueAt(i, 4).toString().trim();
        String sdt = tb_danhSachNhanVien.getValueAt(i, 5).toString().trim();
        String email = tb_danhSachNhanVien.getValueAt(i, 6).toString().trim();
        String matkhau = tb_danhSachNhanVien.getValueAt(i, 7).toString().trim();
        String quyen = tb_danhSachNhanVien.getValueAt(i, 8).toString().trim();


        txt_maNV.setText(manv);
        txt_tenNV.setText(tennv);
        txt_diaChi.setText(diachi);
        txt_gioiTinh.setText(gioitinh);
        txt_ngaySinh.setText(ngaysinh);
        txt_soDT.setText(sdt);
        txt_email.setText(email);
        txt_pass.setText(matkhau);
        txt_quyen.setText(quyen);
    }//GEN-LAST:event_tb_danhSachNhanVienMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnTroLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroLaiActionPerformed
        frm_QuanLyChung qlc = new frm_QuanLyChung(layQuyenNV);
        qlc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTroLaiActionPerformed

    private void btn_xoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaNVActionPerformed
        String manv = txt_maNV.getText();
        String sql = "DELETE FROM NV001.NhanVien WHERE MaNV='" + manv + "'";
        String sql2 = "{CALL NV001.XoaUser('"+ manv +"')}";
        if (NhanVien_DAO.ThemXoaSuaNhanVien(sql) > 0 && NhanVien_DAO.ThemXoaSuaNhanVien(sql2) == 0) {
            dsnv = NhanVien_DAO.LayThongTinNhanVien();
            JOptionPane.showMessageDialog(this,"Thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
            laydulieuNV(dsnv);
        }
    }//GEN-LAST:event_btn_xoaNVActionPerformed

    private void btn_suaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaNVActionPerformed
        String username = txt_maNV.getText().trim();
        String password = String.valueOf(txt_pass.getPassword());
        String hoTen = txt_tenNV.getText().trim();
        String gioiTinh = txt_gioiTinh.getText().trim();
        String ngaySinh = txt_ngaySinh.getText().trim();
        String diaChi = txt_diaChi.getText().trim();
        String sdt = txt_soDT.getText().trim();
        String email = txt_email.getText().trim();
        String quyen = txt_quyen.getText().trim();
        
        String publicKeyBase64 = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAufJotJVB5I6tH62/zGYEg5+BdagJGjTe2D/QSZzAM2R/M0GtKKJa5I1HEX3C84GOXbKjhuU0xQh2otMIS88xbpUeLQ901jr+VSuTYQ+/kys6xO+OCBZ8Z1vEkN5L5QACCW4AOuRrz58fW9WWs881AevsBFS0sJL2/rDxckHwMPaNNQxlWUCnWzAgRhNnYni9GktgTGZQPAZD/eG9dOf5fMFYkcPTP0NXh5X4ZsS2GyGdfY13ILnz1eM09V4LadcqC3fAIWLF9wfQ8qZGdik+DZY5DT7sy38OUqTsuONh3FpUFAbC0jvF/hztpkZp0LPw8Xb12VEXXo5WWLDSdXAejQIDAQAB";
        PublicKey publicKey = null;
        try {
            publicKey = getPublicKey(publicKeyBase64);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(frm_QLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeySpecException ex) {
            Logger.getLogger(frm_QLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {        
                byte[] encryptedSdt = encryptWithPublicKey(sdt, publicKey);
                String MaHoaSDT = Base64.getEncoder().encodeToString(encryptedSdt);
                
            String sql = "{CALL NV001.CapNhatNhanVien('"+username+"', '"+hoTen+"', '"+gioiTinh+"', TO_DATE('" +ngaySinh+ "', 'YYYY-MM-DD'), '"+diaChi+"', '"+MaHoaSDT+"', '"+email+"', '"+quyen+"')}";   
            if (NhanVien_DAO.ThemXoaSuaNhanVien(sql) > 0) 
            {
                dsnv = NhanVien_DAO.LayThongTinNhanVien();
                JOptionPane.showMessageDialog(this,"Update Thành công!","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                laydulieuNV(dsnv);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Update thành công!","Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | BadPaddingException | IllegalBlockSizeException e) {
            e.printStackTrace();
        }    
    }//GEN-LAST:event_btn_suaNVActionPerformed

    private void btn_themNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themNVActionPerformed
        String username = txt_maNV.getText().trim();
        String password = String.valueOf(txt_pass.getPassword());
        String hoTen = txt_tenNV.getText().trim();
        String gioiTinh = txt_gioiTinh.getText().trim();
        String ngaySinh = txt_ngaySinh.getText().trim();
        String diaChi = txt_diaChi.getText().trim();
        String sdt = txt_soDT.getText().trim();
        String email = txt_email.getText().trim();
        String quyen = txt_quyen.getText().trim();
        // Sử dụng khóa công khai từ chuỗi publicKeyBase64
        String publicKeyBase64 = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAufJotJVB5I6tH62/zGYEg5+BdagJGjTe2D/QSZzAM2R/M0GtKKJa5I1HEX3C84GOXbKjhuU0xQh2otMIS88xbpUeLQ901jr+VSuTYQ+/kys6xO+OCBZ8Z1vEkN5L5QACCW4AOuRrz58fW9WWs881AevsBFS0sJL2/rDxckHwMPaNNQxlWUCnWzAgRhNnYni9GktgTGZQPAZD/eG9dOf5fMFYkcPTP0NXh5X4ZsS2GyGdfY13ILnz1eM09V4LadcqC3fAIWLF9wfQ8qZGdik+DZY5DT7sy38OUqTsuONh3FpUFAbC0jvF/hztpkZp0LPw8Xb12VEXXo5WWLDSdXAejQIDAQAB";
        PublicKey publicKey = null;
        try {
            publicKey = getPublicKey(publicKeyBase64);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(frm_QLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeySpecException ex) {
            Logger.getLogger(frm_QLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {        
                byte[] encryptedSdt = encryptWithPublicKey(sdt, publicKey);
                String MaHoaSDT = Base64.getEncoder().encodeToString(encryptedSdt);
                
            String sql = "{CALL NV001.ThemNhanVien_AES('"+username+"', '"+hoTen+"', '"+gioiTinh+"', TO_DATE('" +ngaySinh+ "', 'YYYY-MM-DD'), '"+diaChi+"', '"+MaHoaSDT+"', '"+email+"', '"+password+"', '"+quyen+"')}";

            if (NhanVien_DAO.ThemXoaSuaNhanVien(sql) > 0) {
                NhanVien_DAO.LayThongTinNhanVien();
                JOptionPane.showMessageDialog(this,"Thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                dsnv = NhanVien_DAO.LayThongTinNhanVien(); // Cập nhật danh sách dsnv
                laydulieuNV(dsnv);
            } else {
                JOptionPane.showMessageDialog(this,"Thất bại","Thông báo", JOptionPane.INFORMATION_MESSAGE);            
            }
        } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | BadPaddingException | IllegalBlockSizeException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_themNVActionPerformed

    private void btn_taiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taiLaiActionPerformed
        // TODO add your handling code here:
        NhanVien_DAO.LayThongTinNhanVien();
        dsnv = NhanVien_DAO.LayThongTinNhanVien(); // Cập nhật danh sách dsnv
        laydulieuNV(dsnv);
    }//GEN-LAST:event_btn_taiLaiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        frm_DoiPassword dp = new frm_DoiPassword(layQuyenNV);
        dp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        frm_PhanQuyen pq = new frm_PhanQuyen(layQuyenNV);
        pq.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        frm_PhanNhomQuyen pnq = new frm_PhanNhomQuyen(layQuyenNV);
        pnq.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mn_giamSatTriggerTungPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_giamSatTriggerTungPhanActionPerformed
        // TODO add your handling code here:
        frm_GiamSatTriggerTungPhan gsU2 = new frm_GiamSatTriggerTungPhan(layQuyenNV);
        gsU2.setVisible(true);
        dispose();
    }//GEN-LAST:event_mn_giamSatTriggerTungPhanActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        frm_FGAKhachHang fgaKH = new frm_FGAKhachHang(layQuyenNV);
        fgaKH.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        frm_FGANhanVien fgaNV = new frm_FGANhanVien(layQuyenNV);
        fgaNV.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void mn_giamSatThietBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_giamSatThietBiActionPerformed
        // TODO add your handling code here:
        frm_GiamSatThietBiTruyCap gstbtc = new frm_GiamSatThietBiTruyCap(layQuyenNV);
        gstbtc.setVisible(true);
        dispose();
    }//GEN-LAST:event_mn_giamSatThietBiActionPerformed

    private void mn_giamSatSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_giamSatSAActionPerformed
        // TODO add your handling code here:
        frm_GiamSatSA gsSA = new frm_GiamSatSA(layQuyenNV);
        gsSA.setVisible(true);
        dispose();
    }//GEN-LAST:event_mn_giamSatSAActionPerformed

    private void mn_giamSatAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_giamSatAuditActionPerformed
        // TODO add your handling code here:
        frm_GiamSatKhachHangBangSA gssdSA = new frm_GiamSatKhachHangBangSA(layQuyenNV);
        gssdSA.setVisible(true);
        dispose();
    }//GEN-LAST:event_mn_giamSatAuditActionPerformed

    private void mn_giamSatTriggerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_giamSatTriggerActionPerformed
        // TODO add your handling code here:
        frm_GiamSatTrigger gs = new frm_GiamSatTrigger(layQuyenNV);
        gs.setVisible(true);
        dispose();
    }//GEN-LAST:event_mn_giamSatTriggerActionPerformed

    private void mn_standardAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_standardAuditActionPerformed
        // TODO add your handling code here:
        frm_GiamSatNhanVienBangSA gssdSA = new frm_GiamSatNhanVienBangSA(layQuyenNV);
        gssdSA.setVisible(true);
        dispose();
    }//GEN-LAST:event_mn_standardAuditActionPerformed
    
    private byte[] encryptWithPublicKey(String data, PublicKey publicKey) throws NoSuchAlgorithmException, NoSuchPaddingException,
        InvalidKeyException, BadPaddingException, IllegalBlockSizeException {
        Cipher cipher = Cipher.getInstance("RSA");
        cipher.init(Cipher.ENCRYPT_MODE, publicKey);
        return cipher.doFinal(data.getBytes());
    }
    // Hàm lấy khóa công khai từ chuỗi Base64
    private PublicKey getPublicKey(String publicKeyBase64) throws NoSuchAlgorithmException, InvalidKeySpecException {
        byte[] publicKeyBytes = Base64.getDecoder().decode(publicKeyBase64);
        X509EncodedKeySpec keySpec = new X509EncodedKeySpec(publicKeyBytes);
        KeyFactory keyFactory = KeyFactory.getInstance("RSA");
        return keyFactory.generatePublic(keySpec);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_QLNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTroLai;
    private javax.swing.JButton btn_suaNV;
    private javax.swing.JButton btn_taiLai;
    private javax.swing.JButton btn_themNV;
    private javax.swing.JButton btn_xoaNV;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mn_giamSatAudit;
    private javax.swing.JMenuItem mn_giamSatSA;
    private javax.swing.JMenuItem mn_giamSatThietBi;
    private javax.swing.JMenuItem mn_giamSatTrigger;
    private javax.swing.JMenuItem mn_giamSatTriggerTungPhan;
    private javax.swing.JMenuItem mn_standardAudit;
    private javax.swing.JTable tb_danhSachNhanVien;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_gioiTinh;
    private javax.swing.JTextField txt_maNV;
    private javax.swing.JTextField txt_ngaySinh;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_quyen;
    private javax.swing.JTextField txt_quyen1;
    private javax.swing.JTextField txt_soDT;
    private javax.swing.JTextField txt_tenNV;
    private javax.swing.JTextField txt_timKiemTheoTen;
    // End of variables declaration//GEN-END:variables

}
