/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.GiamSatSA_DAO;
import DAO.NhanVien_DAO;
import POJO.DBA_AUDIT_TRAIL;
import POJO.NhanVien;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class frm_GiamSatKhachHangBangSA extends javax.swing.JFrame {
    Vector tblData2 = new Vector();
    Vector tblTitle2 = new Vector();
    DefaultTableModel tblModel2;
    
    static ArrayList<NhanVien> dsnv = NhanVien_DAO.LayThongTinNhanVien();
    static ArrayList<DBA_AUDIT_TRAIL> dat = GiamSatSA_DAO.LayThongTinGiamSat();
    private String layQuyenNV;
    /**
     * Creates new form frm_GiamSatSuDungSA
     */
    public frm_GiamSatKhachHangBangSA(String layQuyenNV) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        bangGiamSatNV();
        layDuLieuGiamSat(dat);
        
        this.layQuyenNV=layQuyenNV;
        this.txt_quyen1.setText(layQuyenNV); 
    }

    private frm_GiamSatKhachHangBangSA() {
    }
    public void bangGiamSatNV() {
        tblTitle2.add("username");
        tblTitle2.add("timestamp");
        tblTitle2.add("obj_name");
        tblTitle2.add("action_name");
    }
    public void layDuLieuGiamSat(ArrayList<DBA_AUDIT_TRAIL> dat) {
        tblData2.removeAllElements();
        for (DBA_AUDIT_TRAIL a : dat) {
            Vector v = new Vector();
            v.add(a.getUsername());
            v.add(a.getTimestamp());
            v.add(a.getObj_name());
            v.add(a.getAction_name());
            tblData2.add(v);
        }
        tb_GiamSatNV.setModel(new DefaultTableModel(tblData2, tblTitle2));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_tenBang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_quyen1 = new javax.swing.JTextField();
        btn_troVe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_GiamSatNV = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        rdb_select = new javax.swing.JRadioButton();
        rdb_insert = new javax.swing.JRadioButton();
        rdb_update = new javax.swing.JRadioButton();
        rdb_delete = new javax.swing.JRadioButton();
        btn_ApDungTheoTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên bảng:");

        txt_quyen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_quyen1.setEnabled(false);

        btn_troVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_troVe.setText("Trở về");
        btn_troVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_troVeActionPerformed(evt);
            }
        });

        tb_GiamSatNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_GiamSatNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_GiamSatNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_GiamSatNV);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        rdb_select.setText("Select");

        rdb_insert.setText("Insert");

        rdb_update.setText("Update");

        rdb_delete.setText("Delete");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdb_select, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdb_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdb_update, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdb_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdb_select)
                .addGap(18, 18, 18)
                .addComponent(rdb_insert)
                .addGap(18, 18, 18)
                .addComponent(rdb_update)
                .addGap(18, 18, 18)
                .addComponent(rdb_delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_ApDungTheoTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ApDungTheoTable.setText("Áp dụng theo Table");
        btn_ApDungTheoTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ApDungTheoTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_troVe))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_tenBang, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ApDungTheoTable)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_quyen1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_quyen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_tenBang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ApDungTheoTable))
                        .addGap(18, 18, 18)
                        .addComponent(btn_troVe)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_troVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_troVeActionPerformed
        // TODO add your handling code here:
        frm_QLNhanVien qlnv = new frm_QLNhanVien(layQuyenNV);
        qlnv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_troVeActionPerformed

    private void tb_GiamSatNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_GiamSatNVMouseClicked

    }//GEN-LAST:event_tb_GiamSatNVMouseClicked

    private void btn_ApDungTheoTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ApDungTheoTableActionPerformed
        // TODO add your handling code here:
//        String maNV = txt_maNV.getText().trim();
        String table = txt_tenBang.getText().trim();
        
        if(rdb_select.isSelected()==true){
            String sql = "AUDIT SELECT ON NV001."+table+"";         
            if(NhanVien_DAO.ThemXoaSuaNhanVien(sql) == 0 ){            
                JOptionPane.showMessageDialog(this,"Thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);             
            }
        }
        if(rdb_update.isSelected()==true){
            String sql = "AUDIT UPDATE ON NV001."+table+"";         
            if(NhanVien_DAO.ThemXoaSuaNhanVien(sql) == 0 ){            
                JOptionPane.showMessageDialog(this,"Thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);             
            }
        }
        if(rdb_insert.isSelected()==true){
            String sql = "AUDIT INSERT ON NV001."+table+"";         
            if(NhanVien_DAO.ThemXoaSuaNhanVien(sql) == 0 ){            
                JOptionPane.showMessageDialog(this,"Thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);             
            }
        }
        if(rdb_delete.isSelected()==true){
            String sql = "AUDIT DELETE ON NV001."+table+"";         
            if(NhanVien_DAO.ThemXoaSuaNhanVien(sql) == 0 ){            
                JOptionPane.showMessageDialog(this,"Thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);             
            }
        }
    }//GEN-LAST:event_btn_ApDungTheoTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_GiamSatKhachHangBangSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_GiamSatKhachHangBangSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_GiamSatKhachHangBangSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_GiamSatKhachHangBangSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_GiamSatKhachHangBangSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ApDungTheoTable;
    private javax.swing.JButton btn_troVe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdb_delete;
    private javax.swing.JRadioButton rdb_insert;
    private javax.swing.JRadioButton rdb_select;
    private javax.swing.JRadioButton rdb_update;
    private javax.swing.JTable tb_GiamSatNV;
    private javax.swing.JTextField txt_quyen1;
    private javax.swing.JTextField txt_tenBang;
    // End of variables declaration//GEN-END:variables
}
